[phases.setup]
nixPkgs = [
    'nodejs', 
    'python3', 
    'python3Packages.pandas', 
    'python3Packages.scikit-learn', 
    'python3Packages.joblib'
]

[phases.install]
cmds = ['npm install']

[phases.start]
cmd = 'node server.js'