[phases.setup]
nixPkgs = ['nodejs', 'python3', 'stdenv.cc.cc.lib', 'zlib']

[phases.install]
cmds = [
    'npm install',
    'python3 -m venv /app/venv',
    '/app/venv/bin/pip install pandas scikit-learn joblib numpy'
]

[phases.start]
cmd = 'PATH=/app/venv/bin:$PATH node server.js'