[phases.setup]
nixPkgs = ['nodejs', 'python3', 'python311Packages.pip']

[phases.install]
cmds = [
    'npm install',
    'pip install pandas scikit-learn joblib numpy --break-system-packages'
]

[phases.start]
cmd = 'node server.js'